### ISSUE TITLE
카드 결과 페이지 캐릭터 애니메이션 추가 

### ISSUE THREAD

**Issue by tjdgml97** [tjdgml97/PLANT.IT#52]
**Description**
- 캐릭터에 애니메이션 추가 ( 로켓 캐릭터 파일 ) 

**Todo**
- [x]  캐릭터에 애니메이션 추가 
- [x]  텍스트(캐릭터 이름) 애니메이션 추가 
- [x] "식물추천"텍스트에 애니메이션 추가 
- [x] 배치 수정 
- [x] 텍스트에 폰트 추가
