### ISSUE TITLE
오류 수정

### ISSUE THREAD

**Issue by rayodesol** [tjdgml97/PLANT.IT#74]
**Description**
- 오류 수정

**Todo**
- [x] 추천식물 사진 오류
- [x] 로켓 추천식물 사진 추가
- [x] 테스트 -> 테스트 결과 넘어갈 때 뜨는 오류 페이지 수정
- [x] 식물카테고리 로컬스토리지 받아올 때 새로고침 문제 해결

**ETC**
