### ISSUE TITLE
오늘할거

### ISSUE THREAD

**Issue by dbswp** [tjdgml97/PLANT.IT#80]
**Description**
- 오늘할걸 간략하게 설명

**Todo**
- [x] jwt 토큰 발행
- [x]  구글 지도 가져오기
- [x] 카카오 계정 연동

**ETC**
- 기타사항사항
